services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    env_file: .env
